
# import all components from the tkinter library
from tkinter import *
import tkinter as tk
from tkinter import ttk
import copy
import time 
from slaves_modbus_configuration import*
from pymodbus.client import ModbusSerialClient
from modbus_interface import Modbus_Interface
from watchpoints import watch
from rs485_gui_slave import*
from sample_bypass_module import*


### CAVEATS
# modbus cannot handle floating point and negative value data. 
# So for now, floating point values are generated by dividing the variable by 10 and multiplying by 10 to send over modbus as uint16_t 
# We consider ONLY upto one place after decimal for all floating point values.

class SAMPLE_BYPASS():
    def __init__(self, window  = None, rs485_gui_slave = None):
        # Enable module
        # Auto / debug mode : check button
        # tare load cell: Button + Label
        # get_weight: Buttom + Label
        # Set/ Entry box for desired target sample volume/weight
        # Start/ stop sample withdraw, given a flow rate/ PWM value, Pumps to run until we withdraw 150ml of sample
        # Some progress bar to monitor the level/ weight of the sample in the bottle. 
        # Start/ stop sample infusion into centrifuge, given a flow rate/ PWM value. 
        # Same progress bar to denote the sample/ weight level in the bottle
        # Get Humidity and Temperature info, lowest priority                 
        self.window = window             
        self.rs485_gui_slave = rs485_gui_slave                
        self.color = "#d9d9d9"    # Deafult gray color of a widget print("Default color = ", self.gui_dict['Check_dict']['enable_sample_bypass'].cget("bg"))              
        self.gui_dict =  {'Label_dict':{}, 'Text_dict':{}, 'Button_dict':{}, 'Scale_dict':{}, 'Check_dict':{}, 'Drop_down_dict':{}, 'Radio_dict':{}, 'Progress_bar':{}, 'Scale_dict':{} }
        self.gen_sample_bypass_gui()   
        self.current_weight = 0.0
        self.untared_weight = 0.0
        self.tared_weight = 0.0
        self.current_humidity = 0.0
        self.current_temperature = 0.0
        self.current_pump_1_rpm = 0     
        self.current_pump_2_rpm = 0

    def gen_sample_bypass_gui(self):
        self.canvas_height = 800
        self.canvas_width = 800 
        self.canvas = tk.Canvas(self.window, bg="white", height = self.canvas_height, width = self.canvas_width, background= "#d9d9d9",  highlightthickness = 5)  
        self.frame = tk.Frame(self.canvas, width = self.canvas_width-10, height = self.canvas_height-10, background= self.color)        
        self.canvas.create_window( 5, 5, window = self.frame, anchor=tk.NW )         

        width = 40    
        self.gui_dict['Check_dict']['enable_sample_bypass_IntVar'] = IntVar()
        self.gui_dict['Check_dict']['enable_sample_bypass'] = Checkbutton(self.frame, 
                                                                            text="RUN: Sample bypass",
                                                                            variable=self.gui_dict['Check_dict']['enable_sample_bypass_IntVar'],
                                                                            onvalue=True,
                                                                            offvalue=False,
                                                                            height=1, 
                                                                            width = width,
                                                                            command=self.sample_bypass_enable)
                                                                         
        self.gui_dict['Radio_dict']['auto_debug_IntVar'] = StringVar(value="auto")
        self.gui_dict['Radio_dict']['auto'] = tk.Radiobutton(self.frame, text="Auto ", variable=self.gui_dict['Radio_dict']['auto_debug_IntVar'], value="auto", height=1, width = width)
        self.gui_dict['Radio_dict']['debug'] = tk.Radiobutton(self.frame, text="Debug", variable=self.gui_dict['Radio_dict']['auto_debug_IntVar'], value="debug", height=1, width = width)                                                                           
        self.gui_dict['Button_dict']['sample_bypass_start'] = Button(self.frame,
                                                                    text="Start",
                                                                    command=self.sample_bypass_start, 
                                                                    height=1, width = width)

        self.gui_dict['Button_dict']['tare'] = Button(self.frame, text="Tare load cell", command=self.sample_bypass_tare, height=1, width = width)
        self.gui_dict['Button_dict']['get_weight'] = Button(self.frame, text=" Get sample weight ",  command=self.sample_bypass_get_sample_weight, height=1, width = width)
        self.gui_dict['Label_dict']['get_weight'] = Label(self.frame, text="### grams")
        self.gui_dict['Label_dict']['untared_weight'] = Label(self.frame, text="Un-tared weight(grams) = ",  wraplength=400, width = width)
        self.gui_dict['Label_dict']['untared_weight_value'] = Label(self.frame, text="### (grams)")

        self.gui_dict['Label_dict']['set_weight_withdraw'] = Label(self.frame, text="Set sample weight to withdraw (0 to 200 grams)", wraplength=400, width = width)
        self.gui_dict['Scale_dict']['set_weight_withdraw_DoubleVar'] = DoubleVar(value=0.0)
        self.gui_dict['Scale_dict']['set_weight_withdraw'] = Scale(self.frame,
                                                                    variable=self.gui_dict['Scale_dict']['set_weight_withdraw_DoubleVar'],
                                                                    from_= 0, to=200, orient=HORIZONTAL, length=350, border=1, width=20) 

        self.gui_dict['Label_dict']['set_weight_infuse'] = Label(self.frame, text="Set sample weight to infuse (0 to <150 grams)", wraplength=400, width = width)
        self.gui_dict['Scale_dict']['set_weight_infuse_DoubleVar'] = DoubleVar(value=0.0)
        self.gui_dict['Scale_dict']['set_weight_infuse'] = Scale(self.frame, variable=self.gui_dict['Scale_dict']['set_weight_infuse_DoubleVar'],
                                                                    from_=0, to=200,orient=HORIZONTAL, length=350, border=1, width=20)

        self.gui_dict['Label_dict']['set_pump_1_rpm'] = Label(self.frame, text="Set Pump 1 RPM % (0 to 100)", wraplength=250, width = width)
        self.gui_dict['Scale_dict']['set_pump_1_rpm_DoubleVar'] = DoubleVar(value=0)
        self.gui_dict['Scale_dict']['set_pump_1_rpm'] = Scale(self.frame, variable=self.gui_dict['Scale_dict']['set_pump_1_rpm_DoubleVar'],
                                                                    from_=0, to=100,orient=HORIZONTAL, length=350, border=1, width=20)
        self.gui_dict['Label_dict']['set_pump_1_status'] = Label(self.frame, text="Pump 1 OFF", wraplength=300, width = width, bg='orange')

        self.gui_dict['Label_dict']['set_pump_2_rpm'] = Label(self.frame, text="Set Pump 2 RPM % (0 to 100)", wraplength=250, width = width)
        self.gui_dict['Scale_dict']['set_pump_2_rpm_DoubleVar'] = DoubleVar(value=0)
        self.gui_dict['Scale_dict']['set_pump_2_rpm'] = Scale(self.frame, variable=self.gui_dict['Scale_dict']['set_pump_2_rpm_DoubleVar'],
                                                                    from_=0, to=100,orient=HORIZONTAL, length=350, border=1, width=20)        
        self.gui_dict['Label_dict']['set_pump_2_status'] = Label(self.frame, text="Pump 2 OFF", wraplength=300, width = width, bg='orange')                                                                    

        # Withdraw
        self.gui_dict['Check_dict']['start_stop_withdraw_IntVar'] = IntVar(value=0)
        self.gui_dict['Check_dict']['start_stop_withdraw'] = Checkbutton(self.frame,
                                                                        text="   WITHDRAW Sample: Start / Stop",
                                                                        variable=self.gui_dict['Check_dict']['start_stop_withdraw_IntVar'], 
                                                                        onvalue=1,
                                                                        offvalue=0,
                                                                        command=self.sample_bypass_withdraw,
                                                                        height=1,
                                                                        width = width)
        self.gui_dict['Label_dict']['withdraw_status'] = Label(self.frame, text="Standby", wraplength=250, width = width, bg="orange")                                                                        
        self.gui_dict['Progress_bar']['withdraw_progress'] = ttk.Progressbar(self.frame, orient='horizontal', length=400,mode="determinate")

        # Infuse
        self.gui_dict['Check_dict']['start_stop_infuse_IntVar'] = IntVar(value=0)
        self.gui_dict['Check_dict']['start_stop_infuse'] = Checkbutton(self.frame,
                                                                        text="   INFUSE Sample: Start / Stop",
                                                                        variable=self.gui_dict['Check_dict']['start_stop_infuse_IntVar'], 
                                                                        onvalue=1,
                                                                        offvalue=0,
                                                                        command=self.sample_bypass_infuse,
                                                                        height=1,
                                                                        width = width)
        self.gui_dict['Label_dict']['infuse_status'] = Label(self.frame, text="Standby", wraplength=250, width = width, bg="orange")                                                                          
        self.gui_dict['Progress_bar']['infuse_progress'] = ttk.Progressbar(self.frame, orient='horizontal', length=400,mode="determinate")

        self.gui_dict['Label_dict']['humidity_&_temperature'] = Button(self.frame, text="Humidity (RH) \n Temperature (deg C)", command=self.humidity_temperature, width = width)
        self.gui_dict['Label_dict']['humidity_value'] = Label(self.frame, text=" (%)")        
        self.gui_dict['Label_dict']['temperature_value'] = Label(self.frame, text="### deg C")        
        self.gui_dict['Label_dict']['reset_slave'] = Button(self.frame, text="RESET Arduino", command=self.sample_bypass_reset_slave, width = width)

        # Place all the widgets on the self.frame.
        self.canvas.grid(row=0, column=0, sticky="nw", padx=5, pady=50)
        self.gui_dict['Check_dict']['enable_sample_bypass'].grid(row = 0, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Radio_dict']['auto'].grid(row = 1, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Radio_dict']['debug'].grid(row = 2, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Button_dict']['sample_bypass_start'].grid(row = 3, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Button_dict']['tare'].grid(row = 4, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Button_dict']['get_weight'].grid(row = 5, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['get_weight'].grid(row = 5, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['untared_weight'].grid(row = 6, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['untared_weight_value'].grid(row = 6, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['set_weight_withdraw'].grid(row = 7, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Scale_dict']['set_weight_withdraw'].grid(row = 7, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['set_weight_infuse'].grid(row = 8, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Scale_dict']['set_weight_infuse'].grid(row = 8, column = 1, sticky = "nw", pady = 2, columnspan = 1)               
        self.gui_dict['Label_dict']['set_pump_1_rpm'].grid(row = 9, column = 0, sticky = "nw", pady = 2, columnspan = 1)        
        self.gui_dict['Scale_dict']['set_pump_1_rpm'].grid(row = 9, column = 1, sticky = "nw", pady = 2, columnspan = 1)                
        self.gui_dict['Label_dict']['set_pump_2_rpm'].grid(row = 10, column = 0, sticky = "nw", pady = 2, columnspan = 1)        
        self.gui_dict['Scale_dict']['set_pump_2_rpm'].grid(row = 10, column = 1, sticky = "nw", pady = 2, columnspan = 1)             
        self.gui_dict['Check_dict']['start_stop_withdraw'].grid(row = 11, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['withdraw_status'].grid(row = 11, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Progress_bar']['withdraw_progress'].grid(row = 12, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['set_pump_1_status'].grid(row = 12, column = 1, sticky = "nw", pady = 2, columnspan = 1) 
        self.gui_dict['Check_dict']['start_stop_infuse'].grid(row = 13, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['infuse_status'].grid(row = 13, column = 1, sticky = "nw", pady = 2, columnspan = 1)        
        self.gui_dict['Progress_bar']['infuse_progress'].grid(row = 14, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['set_pump_2_status'].grid(row = 14, column = 1, sticky = "nw", pady = 2, columnspan = 1)     
        self.gui_dict['Label_dict']['humidity_&_temperature'].grid(row = 15, column = 0, sticky = "nw", pady = 2, columnspan = 1, rowspan = 2)
        self.gui_dict['Label_dict']['humidity_value'].grid(row = 15, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        # self.gui_dict['Label_dict']['temperature'].grid(row = 16, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['temperature_value'].grid(row = 16, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['reset_slave'].grid(row = 17, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        print("Complete gen_gui()")

    # Send a software reset trigger to the slave. Arduino resets the value: the coils_list[6] = 0. 
    def sample_bypass_reset_slave(self):        
        self.rs485_gui_slave.coils_list[6] = 1                        
        self.rs485_gui_slave.update_slave_via_reg_list()
        self.rs485_gui_slave.update_gui()                  

    def sample_bypass_enable(self):
        pass

    def sample_bypass_start(self):
        pass
    
    # Function to Tare the load cell.
    def sample_bypass_tare(self):
        # This is to tare the weight on the Arduino side:
        # arduino resets this values to 0 in the array_coil_list[5]
        self.rs485_gui_slave.coils_list[5] = 1   
        self.sample_bypass_get_sample_weight()        

    # Function to get the sample weight, default in arduino code is to get 5 sample and return average.
    def sample_bypass_get_sample_weight(self):
        self.rs485_gui_slave.coils_list[2] = 1                
        self.rs485_gui_slave.update_gui()
        self.rs485_gui_slave.update_slave_via_reg_list()
               
        self.untared_weight = copy.deepcopy(self.rs485_gui_slave.input_reg_list[3])
        self.current_weight = self.rs485_gui_slave.input_reg_list[2] - self.untared_weight     # Update the input reg, float value    
        # self.current_weight = copy.deepcopy(self.rs485_gui_slave.input_reg_list[2])     # Update the input reg, float value             
        
        # Update GUI with reading        
        self.gui_dict['Label_dict']['untared_weight_value'].configure(text=str(round(self.untared_weight,2)) + " (grams)" )                
        self.gui_dict['Label_dict']['get_weight'].configure(text = str(round(self.current_weight,2))) # float value
        self.window.update()

        # Note: empty weight of the glass bottle with tubing...etc is about 585.5 grams.

    def sample_bypass_withdraw(self): 
        self.gui_dict['Label_dict']['withdraw_status'].config(text="Started", bg="light blue")
        self.sample_bypass_get_sample_weight()                  
        target_weight = self.gui_dict['Scale_dict']['set_weight_withdraw_DoubleVar'].get()   # Returns float
              
        total = target_weight + self.untared_weight
        if self.current_weight <= 200 and total <= 750.0:
            print("In sample_bypass_withdraw(): Total weight (g) = ", total)           
        else:
            print("In sample_bypass_withdraw(): The target weight is more that total weight threshold.")
            print("     total weight (g) = ", total )
            print("CANNOT WITHDRAW SAMPLE")
            self.gui_dict['Label_dict']['withdraw_status'].config(text="Total weight exceeds capacity", bg="red")
            return                         

        # There are two states of the checkbox
        # if checkbox is True, do stuff
        if self.gui_dict['Check_dict']['start_stop_withdraw_IntVar'].get() == 1:            
            self.gui_dict['Progress_bar']['withdraw_progress']['value'] = 0           # Clear the progress bar
            time_start = copy.deepcopy(time.time())      # Start a timer

            while True:
                time_stop = copy.deepcopy(time.time())   # Get present time
                self.sample_bypass_get_sample_weight()                     

                # Check if current weight is greater than or equal to target weight to switch off the pump. 
                if target_weight <= self.current_weight:
                    print("In sample_bypass_withdraw(): Sample target weight withdrawn.")
                    print("In sample_bypass_withdraw(): Turning pump 1 OFF.")
                    self.rs485_gui_slave.coils_list[3] = 0              # Pump 1 enable set to OFF,                          
                    self.rs485_gui_slave.holding_reg_list[0] = 0        # Switch OFF motor
                    self.rs485_gui_slave.update_gui()
                    self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave 
                    self.gui_dict['Label_dict']['set_pump_1_status'].configure(text="Pump 1 OFF", bg="orange")
                    self.gui_dict['Label_dict']['withdraw_status'].config(text="Completed", bg="light green")
                    break
                # Else, we update progress bar, and monitor the current weight.
                else:
                    # Enable the pump to withdraw with a user entered RPM in realtime          
                    pump_1_rpm = int(self.gui_dict['Scale_dict']['set_pump_1_rpm_DoubleVar'].get())      # Returns a float value from slider, we convert to int for holding reg
                    self.rs485_gui_slave.coils_list[3] = 1  # Pump 1 enable set to ON                        
                    self.rs485_gui_slave.holding_reg_list[0] = pump_1_rpm   # Switch ON motor
                    self.rs485_gui_slave.update_gui()
                    self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave
                    self.gui_dict['Label_dict']['set_pump_1_status'].configure(text="Pump 1 ON", bg="green")                                     
                    self.gui_dict['Progress_bar']['withdraw_progress']['value'] = int((self.current_weight/target_weight) * 100) # weight progress
                    # self.gui_dict['Progress_bar']['withdraw_progress']['value'] = int((time_stop - time_start) * 10)     # dummy / debug to see the progress bar move for time's progress

                # Break out of the loop after 10 seconds
                # At 100% RPM with 12V adapter, the pump can withdraw sample in about 25 seconds, so we set a timeout for 30 seconds. 
                # The timeout needs to be proportional to the target volume.
                # assumption: 100ml can be withdrawn in about 30seconds, thus x ml would take 20 * x ml/100. leeway of 2 seconds 
                if (time_stop - time_start) >= int(target_weight * 32/100):
                    print("In sample_bypass_withdraw(): Sample withdrawal timeout !")
                    print("In sample_bypass_withdraw(): Turning pump 1 OFF.")
                    self.rs485_gui_slave.coils_list[3] = 0              # Pump 1 enable set to OFF,                          
                    self.rs485_gui_slave.holding_reg_list[0] = 0        # Switch OFF motor
                    self.rs485_gui_slave.update_gui()
                    self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave                     
                    self.gui_dict['Label_dict']['set_pump_1_status'].configure(text="Pump 1 OFF", bg="orange")
                    self.gui_dict['Label_dict']['withdraw_status'].config(text="TIMEOUT !", bg="light blue")
                    break
                else:
                    self.gui_dict['Label_dict']['withdraw_status'].config(text="Timer: " + str(round(time_stop - time_start,2)), bg="light blue")

                self.window.update()
        # else if checkbox is False , Turn off pump 1
        else:  
            self.rs485_gui_slave.coils_list[3] = 0          # Pump 1 enable set to OFF                        
            self.rs485_gui_slave.holding_reg_list[0] = 0    # Switch ON motor
            self.rs485_gui_slave.update_gui()
            self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave
            self.gui_dict['Label_dict']['set_pump_1_status'].configure(text="Pump 1 OFF", bg="orange")
            self.gui_dict['Label_dict']['withdraw_status'].config(text="Standby", bg="orange")
            print("In sample_bypass_withdraw(): Switched OFF pump 1")          

    def sample_bypass_infuse(self): 
            self.gui_dict['Label_dict']['infuse_status'].config(text="Started", bg="light blue")
            self.sample_bypass_get_sample_weight()                  
            target_weight = self.gui_dict['Scale_dict']['set_weight_infuse_DoubleVar'].get()   # Returns float
            initial_weight = copy.deepcopy(self.current_weight)        # Since we have to do subtraction later. 
            print("In sample_bypass_infuse(): Current weight ", self.current_weight)

            self.gui_dict['Progress_bar']['infuse_progress']['value'] = 0

            # The target weight to be infused needs to be less than the current weight           
            if self.current_weight < target_weight:
                print("In sample_bypass_infuse(): The target weight is more than current weight.")                
                print("CANNOT infuse SAMPLE")
                self.gui_dict['Label_dict']['infuse_status'].config(text="Current weight < Target weight", bg="red")
                return            
            else:
                print("In sample_bypass_infuse(): System will infuse target weight of ", target_weight, " (g)")               

            # There are two states of the checkbox
            # if checkbox is True, do stuff
            if self.gui_dict['Check_dict']['start_stop_infuse_IntVar'].get() == 1:
                # Clear the progress bar
                self.gui_dict['Progress_bar']['infuse_progress']['value'] = target_weight
            
                time_start = copy.deepcopy(time.time())      # Start a timer                
                while True:
                    time_stop = copy.deepcopy(time.time())   # Get present time
                    self.sample_bypass_get_sample_weight()  
                    infused_weight = initial_weight - self.current_weight       

                    # Enable the pump to infuse with a user entered RPM in realtime          
                    pump_2_rpm = int(self.gui_dict['Scale_dict']['set_pump_2_rpm_DoubleVar'].get())      # Returns a float value from slider, we convert to int for holding reg
                    self.rs485_gui_slave.coils_list[4] = 1  # Pump 2 enable set to ON                        
                    self.rs485_gui_slave.holding_reg_list[1] = pump_2_rpm   # Switch ON motor
                    self.rs485_gui_slave.update_gui()
                    self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave
                    self.gui_dict['Label_dict']['set_pump_2_status'].configure(text="Pump 2 ON", bg="green")                                        

                    # We check if the infused weight 
                    if target_weight <= infused_weight:
                        print("In sample_bypass_infuse(): Sample target weight infuse.")
                        print("In sample_bypass_infuse(): Turning Pump 2 OFF.")
                        self.rs485_gui_slave.coils_list[4] = 0              # Pump 2 enable set to OFF,                          
                        self.rs485_gui_slave.holding_reg_list[1] = 0        # Switch OFF motor
                        self.rs485_gui_slave.update_gui()
                        self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave 
                        self.gui_dict['Label_dict']['set_pump_2_status'].configure(text="Pump 2 OFF", bg="orange")
                        self.gui_dict['Label_dict']['infuse_status'].config(text="Completed", bg="light green")
                        break
                    # Else, we update progress bar, and monitor the current weight.
                    else:
                        # self.gui_dict['Progress_bar']['infuse_progress']['value'] = int((time_stop - time_start) * 10)     # time progress
                        self.gui_dict['Progress_bar']['infuse_progress']['value'] = int(target_weight - infused_weight)      # infuse progress
                        # self.gui_dict['Progress_bar']['infuse_progress']['value'] = int((infused_weight/target_weight) * 100) # weight progress

                    # Break out of the loop after 10 seconds
                    if (time_stop - time_start) >= int(target_weight * 32/100):
                        print("In sample_bypass_infuse(): Sample infuse timeout !")
                        print("In sample_bypass_infuse(): Turning Pump 2 OFF.")
                        self.rs485_gui_slave.coils_list[4] = 0              # Pump 2 enable set to OFF,                          
                        self.rs485_gui_slave.holding_reg_list[1] = 0        # Switch OFF motor
                        self.rs485_gui_slave.update_gui()
                        self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave                     
                        self.gui_dict['Label_dict']['set_pump_2_status'].configure(text="Pump 2 OFF", bg="orange")
                        self.gui_dict['Label_dict']['infuse_status'].config(text="TIMEOUT !", bg="light blue")
                        break
                    else:
                        self.gui_dict['Label_dict']['infuse_status'].config(text="Timer: " + str(round(time_stop - time_start,2)), bg="light blue")
                    
                    self.window.update()
            # else if checkbox is False , Turn off Pump 2
            else:  
                self.rs485_gui_slave.coils_list[4] = 0          # Pump 2 enable set to OFF                        
                self.rs485_gui_slave.holding_reg_list[1] = 0    # Switch ON motor
                self.rs485_gui_slave.update_gui()
                self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave
                self.gui_dict['Label_dict']['set_pump_2_status'].configure(text="Pump 2 OFF", bg="orange")
                self.gui_dict['Label_dict']['infuse_status'].config(text="Standby", bg="orange")
                print("In sample_bypass_infuse(): Switched OFF Pump 2")          

    def humidity_temperature(self):
        self.rs485_gui_slave.coils_list[1] = 1          
        self.rs485_gui_slave.update_gui()
        self.rs485_gui_slave.update_slave_via_reg_list()
        self.gui_dict['Label_dict']['humidity_value'].configure(text= str(self.rs485_gui_slave.input_reg_list[0]) + "%")     # Update input_reg
        self.gui_dict['Label_dict']['temperature_value'].configure(text= str(self.rs485_gui_slave.input_reg_list[1]))  # Update input_reg
        
        # Need to set self.rs485_gui_slave.coils_list[1] = 0, else arduino will run the void get_temp_hum() in void loop()
        self.rs485_gui_slave.coils_list[1] = 0          
        self.rs485_gui_slave.update_gui()
        self.rs485_gui_slave.update_slave_via_reg_list()        

    # Function to blink a widget
    def blink(self, widget, blink_num, color):
        for i in range(0,blink_num):
            widget.configure(bg=color)
            self.window.after(100, self.wait_time())
            self.window.update()
            widget.configure(bg="white")
            self.window.after(100, self.wait_time())
            self.window.update()                

    def wait_time(self, *args):
        pass         

def root_window_bind_callback():
    print("In root_window_bind_callback():  ...")
    
def on_closing():
    print("destroying main window.")
    root_window.destroy()       # main
    exit()     


if __name__ == "__main__":
    # Create the root window
    root_window = Tk()   
    root_window.title('DigiFoods - Inline Sensing')       # Set window title    
    window_width = 1600
    window_height = 1000
    root_window.geometry(str(window_width) + "x" + str(window_height))     # Set window size width x height   1600x1000
    # root_window.geometry("1600x1000")     # Set window size width x height   
    root_window.config(background = "white")     #Set window background color  
    root_window.columnconfigure( 0, weight = 1 ) # Stretch Column 0 to fit width.
    root_window.rowconfigure( 0, weight = 1 ) # Stretch row 0 to fit height. 
    root_window.resizable(width=False, height=False)         # This makes the GUI of fixed size and prevents resizing.
    root_window.bind('<Return>', root_window_bind_callback )            # This gets the values entered in the gui.
    root_window.lift()       # Bring window forwards
    # root_window.attributes('-topmost', True)
    root_window.protocol("WM_DELETE_WINDOW", on_closing)   

    slaves_mcfg = Slaves_Modbus_Config()       # Get configurations of all slaves (read xlsx file)
    slaves_mcfg.get_config()
    mi = Modbus_Interface()     # Create a RS485 Modbus RTU interface with baud rate, 8N1 ...etc. 


