
# import all components from the tkinter library
from tkinter import *
# from tkinter import filedialog
# from tkinter.filedialog import asksaveasfile
# from os import walk
# from tkinter import messagebox
import tkinter as tk
# import tkinter.font as tkFont
from tkinter import ttk
import copy
import time 
from slaves_modbus_configuration import*
from pymodbus.client import ModbusSerialClient
from modbus_interface import Modbus_Interface
from watchpoints import watch
from rs485_gui_slave import*

### CAVEATS
# modbus cannot handle floating point and negative value data. 
# So for now, floating point values are generated by dividing the variable by 10 and multiplying by 10 to send over modbus as uint16_t 
# We consider ONLY upto one place after decimal for all floating point values.

class SAMPLE_BYPASS():
    def __init__(self, window  = None, rs485_gui_slave = None):
        # Enable module
        # Auto / debug mode : check button
        # tare load cell: Button + Label
        # get_weight: Buttom + Label
        # Set/ Entry box for desired target sample volume/weight
        # Start/ stop sample withdraw, given a flow rate/ PWM value, Pumps to run until we withdraw 150ml of sample
        # Some progress bar to monitor the level/ weight of the sample in the bottle. 
        # Start/ stop sample infusion into centrifuge, given a flow rate/ PWM value. 
        # Same progress bar to denote the sample/ weight level in the bottle
        # Get Humidity and Temperature info, lowest priority                 
        self.window = window             
        self.rs485_gui_slave = rs485_gui_slave                
        self.color = "#d9d9d9"    # Deafult gray color of a widget print("Default color = ", self.gui_dict['Check_dict']['enable_sample_bypass'].cget("bg"))              
        self.gui_dict =  {'Label_dict':{}, 'Text_dict':{}, 'Button_dict':{}, 'Scale_dict':{}, 'Check_dict':{}, 'Drop_down_dict':{}, 'Radio_dict':{}, 'Progress_bar':{}, 'Scale_dict':{} }
        self.gen_sample_bypass_gui()   
        self.current_weight = 0.0
        self.current_humidity = 0.0
        self.current_temperature = 0.0
        self.current_pump_1_rpm = 0     
        self.current_pump_2_rpm = 0

    def gen_sample_bypass_gui(self):
        self.canvas_height = 800
        self.canvas_width = 800 
        self.canvas = tk.Canvas(self.window, bg="white", height = self.canvas_height, width = self.canvas_width, background= "#d9d9d9",  highlightthickness = 5)  
        self.frame = tk.Frame(self.canvas, width = self.canvas_width-10, height = self.canvas_height-10, background= self.color)        
        self.canvas.create_window( 5, 5, window = self.frame, anchor=tk.NW )         

        width = 40    
        self.gui_dict['Check_dict']['enable_sample_bypass_IntVar'] = IntVar()
        self.gui_dict['Check_dict']['enable_sample_bypass'] = Checkbutton(self.frame, 
                                                                            text="RUN: Sample bypass",
                                                                            variable=self.gui_dict['Check_dict']['enable_sample_bypass_IntVar'],
                                                                            onvalue=True,
                                                                            offvalue=False,
                                                                            height=1, 
                                                                            width = width,
                                                                            command=self.sample_bypass_enable)
                                                                         
        self.gui_dict['Radio_dict']['auto_debug_IntVar'] = StringVar(value="auto")
        self.gui_dict['Radio_dict']['auto'] = tk.Radiobutton(self.frame, text="Auto ", variable=self.gui_dict['Radio_dict']['auto_debug_IntVar'], value="auto", height=1, width = width)
        self.gui_dict['Radio_dict']['debug'] = tk.Radiobutton(self.frame, text="Debug", variable=self.gui_dict['Radio_dict']['auto_debug_IntVar'], value="debug", height=1, width = width)                                                                           
        self.gui_dict['Button_dict']['sample_bypass_start'] = Button(self.frame,
                                                                    text="Start",
                                                                    command=self.sample_bypass_start, 
                                                                    height=1, width = width)

        self.gui_dict['Button_dict']['tare'] = Button(self.frame, text="Tare load cell", command=self.sample_bypass_tare, height=1, width = width)
        self.gui_dict['Button_dict']['get_weight'] = Button(self.frame, text=" Get sample weight ",  command=self.sample_bypass_get_sample_weight, height=1, width = width)
        self.gui_dict['Label_dict']['get_weight'] = Label(self.frame, text="### grams")

        self.gui_dict['Label_dict']['set_weight_withdraw'] = Label(self.frame, text="Set sample weight to withdraw (0 to 200 grams)", wraplength=400, width = width)
        self.gui_dict['Scale_dict']['set_weight_withdraw_DoubleVar'] = DoubleVar(value=0.0)
        self.gui_dict['Scale_dict']['set_weight_withdraw'] = Scale(self.frame,
                                                                    variable=self.gui_dict['Scale_dict']['set_weight_withdraw_DoubleVar'],
                                                                    from_= 0, to=100, orient=HORIZONTAL, length=250, border=1, width=20) 

        self.gui_dict['Label_dict']['set_weight_infuse'] = Label(self.frame, text="Set sample weight to infuse (0 to <150 grams)", wraplength=400, width = width)
        self.gui_dict['Scale_dict']['set_weight_infuse_DoubleVar'] = DoubleVar(value=0.0)
        self.gui_dict['Scale_dict']['set_weight_infuse'] = Scale(self.frame, variable=self.gui_dict['Scale_dict']['set_weight_infuse_DoubleVar'],
                                                                    from_=0, to=100,orient=HORIZONTAL, length=250, border=1, width=20)

        self.gui_dict['Label_dict']['set_pump_1_rpm'] = Label(self.frame, text="Set Pump 1 RPM % (0 to 100)", wraplength=250, width = width)
        self.gui_dict['Scale_dict']['set_pump_1_rpm_DoubleVar'] = DoubleVar(value=0)
        self.gui_dict['Scale_dict']['set_pump_1_rpm'] = Scale(self.frame, variable=self.gui_dict['Scale_dict']['set_pump_1_rpm_DoubleVar'],
                                                                    from_=0, to=100,orient=HORIZONTAL, length=250, border=1, width=20)
        self.gui_dict['Label_dict']['set_pump_1_status'] = Label(self.frame, text="Pump 1 OFF", wraplength=300, width = width, bg='orange')

        self.gui_dict['Label_dict']['set_pump_2_rpm'] = Label(self.frame, text="Set Pump 2 RPM % (0 to 100)", wraplength=250, width = width)
        self.gui_dict['Scale_dict']['set_pump_2_rpm_DoubleVar'] = DoubleVar(value=0)
        self.gui_dict['Scale_dict']['set_pump_2_rpm'] = Scale(self.frame, variable=self.gui_dict['Scale_dict']['set_pump_2_rpm_DoubleVar'],
                                                                    from_=0, to=100,orient=HORIZONTAL, length=250, border=1, width=20)        
        self.gui_dict['Label_dict']['set_pump_2_status'] = Label(self.frame, text="Pump 2 OFF", wraplength=300, width = width, bg='orange')                                                                    

        # Withdraw
        self.gui_dict['Check_dict']['start_stop_withdraw_IntVar'] = IntVar(value=0)
        self.gui_dict['Check_dict']['start_stop_withdraw'] = Checkbutton(self.frame,
                                                                        text="   WITHDRAW Sample: Start / Stop",
                                                                        variable=self.gui_dict['Check_dict']['start_stop_withdraw_IntVar'], 
                                                                        onvalue=1,
                                                                        offvalue=0,
                                                                        command=self.sample_bypass_withdraw,
                                                                        height=1,
                                                                        width = width)
        self.gui_dict['Label_dict']['withdraw_status'] = Label(self.frame, text="Standby", wraplength=250, width = width, bg="orange")                                                                        
        self.gui_dict['Progress_bar']['withdraw_progress'] = ttk.Progressbar(self.frame, orient='horizontal', length=400,mode="determinate")

        # Infuse
        self.gui_dict['Check_dict']['start_stop_infuse_IntVar'] = IntVar(value=0)
        self.gui_dict['Check_dict']['start_stop_infuse'] = Checkbutton(self.frame,
                                                                        text="   INFUSE Sample: Start / Stop",
                                                                        variable=self.gui_dict['Check_dict']['start_stop_infuse_IntVar'], 
                                                                        onvalue=1,
                                                                        offvalue=0,
                                                                        command=self.sample_bypass_infuse,
                                                                        height=1,
                                                                        width = width)
        self.gui_dict['Label_dict']['infuse_status'] = Label(self.frame, text="Standby", wraplength=250, width = width, bg="orange")                                                                          
        self.gui_dict['Progress_bar']['infuse_progress'] = ttk.Progressbar(self.frame, orient='horizontal', length=400,mode="determinate")

        self.gui_dict['Label_dict']['humidity_&_temperature'] = Button(self.frame, text="Humidity (RH) \n Temperature (deg C)", command=self.humidity_temperature, width = width)
        self.gui_dict['Label_dict']['humidity_value'] = Label(self.frame, text=" (%)")        
        self.gui_dict['Label_dict']['temperature_value'] = Label(self.frame, text="### deg C")        

        # Place all the widgets on the self.frame.
        self.canvas.grid(row=0, column=0, sticky="nw", padx=5, pady=50)
        self.gui_dict['Check_dict']['enable_sample_bypass'].grid(row = 0, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Radio_dict']['auto'].grid(row = 1, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Radio_dict']['debug'].grid(row = 2, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Button_dict']['sample_bypass_start'].grid(row = 3, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Button_dict']['tare'].grid(row = 4, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Button_dict']['get_weight'].grid(row = 5, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['get_weight'].grid(row = 5, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['set_weight_withdraw'].grid(row = 6, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Scale_dict']['set_weight_withdraw'].grid(row = 6, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['set_weight_infuse'].grid(row = 7, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Scale_dict']['set_weight_infuse'].grid(row = 7, column = 1, sticky = "nw", pady = 2, columnspan = 1)               
        self.gui_dict['Label_dict']['set_pump_1_rpm'].grid(row = 8, column = 0, sticky = "nw", pady = 2, columnspan = 1)        
        self.gui_dict['Scale_dict']['set_pump_1_rpm'].grid(row = 8, column = 1, sticky = "nw", pady = 2, columnspan = 1)                
        self.gui_dict['Label_dict']['set_pump_2_rpm'].grid(row = 9, column = 0, sticky = "nw", pady = 2, columnspan = 1)        
        self.gui_dict['Scale_dict']['set_pump_2_rpm'].grid(row = 9, column = 1, sticky = "nw", pady = 2, columnspan = 1)             
        self.gui_dict['Check_dict']['start_stop_withdraw'].grid(row = 10, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['withdraw_status'].grid(row = 10, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Progress_bar']['withdraw_progress'].grid(row = 11, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['set_pump_1_status'].grid(row = 11, column = 1, sticky = "nw", pady = 2, columnspan = 1) 
        self.gui_dict['Check_dict']['start_stop_infuse'].grid(row = 12, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['infuse_status'].grid(row = 12, column = 1, sticky = "nw", pady = 2, columnspan = 1)        
        self.gui_dict['Progress_bar']['infuse_progress'].grid(row = 13, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['set_pump_2_status'].grid(row = 13, column = 1, sticky = "nw", pady = 2, columnspan = 1)     
        self.gui_dict['Label_dict']['humidity_&_temperature'].grid(row = 14, column = 0, sticky = "nw", pady = 2, columnspan = 1, rowspan = 2)
        self.gui_dict['Label_dict']['humidity_value'].grid(row = 14, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        # self.gui_dict['Label_dict']['temperature'].grid(row = 15, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['temperature_value'].grid(row = 15, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        print("Complete gen_gui()")

    def sample_bypass_enable(self):
        pass

    def sample_bypass_start(self):
        pass
    
    # Function to Tare the load cell.
    def sample_bypass_tare(self):
        self.rs485_gui_slave.coils_list[5] = 1                
        self.rs485_gui_slave.update_gui()
        self.rs485_gui_slave.update_slave_via_reg_list()

    # Function to get the sample weight, default in arduino code is to get 5 sample and return average.
    def sample_bypass_get_sample_weight(self):
        self.rs485_gui_slave.coils_list[2] = 1                
        self.rs485_gui_slave.update_gui()
        self.rs485_gui_slave.update_slave_via_reg_list()
        self.current_weight = self.rs485_gui_slave.input_reg_list[2]     # Update the input reg, float value     

        # update GUI with reading
        self.gui_dict['Label_dict']['get_weight'].configure(text = str(self.current_weight)) # float value
        self.window.update()

    def sample_bypass_withdraw(self): 
        self.gui_dict['Label_dict']['withdraw_status'].config(text="Started", bg="light blue")
        self.sample_bypass_get_sample_weight()                  
        target_weight = self.gui_dict['Scale_dict']['set_weight_withdraw_DoubleVar'].get()   # Returns float

        # We need to check if the present weight is sufficient to withdraw more sample, threshold is 200 grams
        total = target_weight + self.current_weight
        if 200 <= total:
            print("In sample_bypass_withdraw(): The target weight is more that total weight threshold.")
            print("     total weight (g) = ", total )
            print("CANNOT WITHDRAW SAMPLE")
            self.gui_dict['Label_dict']['withdraw_status'].config(text="Started", bg="red")
            return            
        else:
            print("In sample_bypass_withdraw(): Total weight (g) = ", total)

        # There are two states of the checkbox
        # if checkbox is True, do stuff
        if self.gui_dict['Check_dict']['start_stop_withdraw_IntVar'].get() == 1:
            # Enable the pump to withdraw with a user entered RPM            
            pump_1_rpm = int(self.gui_dict['Scale_dict']['set_pump_1_rpm_DoubleVar'].get())      # Returns a float value from slider, we convert to int for holding reg
            self.rs485_gui_slave.coils_list[3] = 1  # Pump 1 enable set to ON                        
            self.rs485_gui_slave.holding_reg_list[0] = pump_1_rpm   # Switch ON motor
            self.rs485_gui_slave.update_gui()
            self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave
            self.gui_dict['Label_dict']['set_pump_1_status'].configure(text="Pump 1 ON", bg="green")

            # Clear the progress bar
            self.gui_dict['Progress_bar']['withdraw_progress']['value'] = 0
           
            time_start = copy.deepcopy(time.time())      # Start a timer
            while True:
                time_stop = copy.deepcopy(time.time())   # Get present time

                self.sample_bypass_get_sample_weight()                               

                # Check if current weight is greater than or equal to target weight to switch off the pump. 
                if target_weight <= self.current_weight:
                    print("In sample_bypass_withdraw(): Sample target weight withdrawn.")
                    print("In sample_bypass_withdraw(): Turning pump 1 OFF.")
                    self.rs485_gui_slave.coils_list[3] = 0              # Pump 1 enable set to OFF,                          
                    self.rs485_gui_slave.holding_reg_list[0] = 0        # Switch OFF motor
                    self.rs485_gui_slave.update_gui()
                    self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave 
                    self.gui_dict['Label_dict']['set_pump_1_status'].configure(text="Pump 1 OFF", bg="orange")
                    self.gui_dict['Label_dict']['withdraw_status'].config(text="Completed", bg="light green")
                    break
                # Else, we update progress bar, and monitor the current weight.
                else:
                    # self.gui_dict['Progress_bar']['withdraw_progress']['value'] = int((time_stop - time_start) * 10)     # time progress
                    self.gui_dict['Progress_bar']['withdraw_progress']['value'] = int((self.current_weight/target_weight) * 100) # weight progress

                # Break out of the loop after 10 seconds
                if (time_stop - time_start) >= 10:
                    print("In sample_bypass_withdraw(): Sample withdrawal timeout !")
                    print("In sample_bypass_withdraw(): Turning pump 1 OFF.")
                    self.rs485_gui_slave.coils_list[3] = 0              # Pump 1 enable set to OFF,                          
                    self.rs485_gui_slave.holding_reg_list[0] = 0        # Switch OFF motor
                    self.rs485_gui_slave.update_gui()
                    self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave                     
                    self.gui_dict['Label_dict']['set_pump_1_status'].configure(text="Pump 1 OFF", bg="orange")
                    self.gui_dict['Label_dict']['withdraw_status'].config(text="TIMEOUT !", bg="light blue")
                    break
                else:
                    self.gui_dict['Label_dict']['withdraw_status'].config(text="Timer: " + str(round(time_stop - time_start,2)), bg="light blue")
        # else if checkbox is False , Turn off pump 1
        else:  
            self.rs485_gui_slave.coils_list[3] = 0          # Pump 1 enable set to OFF                        
            self.rs485_gui_slave.holding_reg_list[0] = 0    # Switch ON motor
            self.rs485_gui_slave.update_gui()
            self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave
            self.gui_dict['Label_dict']['set_pump_1_status'].configure(text="Pump 1 OFF", bg="orange")
            self.gui_dict['Label_dict']['withdraw_status'].config(text="Standby", bg="orange")
            print("In sample_bypass_withdraw(): Switched OFF pump 1")          

    def sample_bypass_infuse(self): 
            self.gui_dict['Label_dict']['infuse_status'].config(text="Started", bg="light blue")
            self.sample_bypass_get_sample_weight()                  
            target_weight = self.gui_dict['Scale_dict']['set_weight_infuse_DoubleVar'].get()   # Returns float
            initial_weight = copy.deepcopy(self.current_weight)        # Since we have to do subtraction later. 
            print("Current weight ", self.current_weight)

            self.gui_dict['Progress_bar']['infuse_progress']['value'] = 0

            # The target weight to be infused needs to be less than the current weight           
            if self.current_weight < target_weight:
                print("In sample_bypass_infuse(): The target weight is more than current weight.")                
                print("CANNOT infuse SAMPLE")
                self.gui_dict['Label_dict']['infuse_status'].config(text="Current weight < Target weight", bg="red")
                return            
            else:
                print("In sample_bypass_infuse(): System will infuse target weight of ", target_weight, " (g)")               

            # There are two states of the checkbox
            # if checkbox is True, do stuff
            if self.gui_dict['Check_dict']['start_stop_infuse_IntVar'].get() == 1:
                # Enable the pump to infuse with a user entered RPM            
                pump_2_rpm = int(self.gui_dict['Scale_dict']['set_pump_2_rpm_DoubleVar'].get())      # Returns a float value from slider, we convert to int for holding reg
                self.rs485_gui_slave.coils_list[4] = 1  # Pump 2 enable set to ON                        
                self.rs485_gui_slave.holding_reg_list[1] = pump_2_rpm   # Switch ON motor
                self.rs485_gui_slave.update_gui()
                self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave
                self.gui_dict['Label_dict']['set_pump_2_status'].configure(text="Pump 2 ON", bg="green")

                # Clear the progress bar
                self.gui_dict['Progress_bar']['infuse_progress']['value'] = target_weight
            
                time_start = copy.deepcopy(time.time())      # Start a timer                
                while True:
                    time_stop = copy.deepcopy(time.time())   # Get present time
                    self.sample_bypass_get_sample_weight()  
                    infused_weight = initial_weight - self.current_weight                           

                    # We check if the infused weight 
                    if target_weight <= infused_weight:
                        print("In sample_bypass_infuse(): Sample target weight infusen.")
                        print("In sample_bypass_infuse(): Turning Pump 2 OFF.")
                        self.rs485_gui_slave.coils_list[4] = 0              # Pump 2 enable set to OFF,                          
                        self.rs485_gui_slave.holding_reg_list[1] = 0        # Switch OFF motor
                        self.rs485_gui_slave.update_gui()
                        self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave 
                        self.gui_dict['Label_dict']['set_pump_2_status'].configure(text="Pump 2 OFF", bg="orange")
                        self.gui_dict['Label_dict']['infuse_status'].config(text="Completed", bg="light green")
                        break
                    # Else, we update progress bar, and monitor the current weight.
                    else:
                        # self.gui_dict['Progress_bar']['infuse_progress']['value'] = int((time_stop - time_start) * 10)     # time progress
                        self.gui_dict['Progress_bar']['infuse_progress']['value'] = int(target_weight - infused_weight)      # infuse progress
                        # self.gui_dict['Progress_bar']['infuse_progress']['value'] = int((infused_weight/target_weight) * 100) # weight progress

                    # Break out of the loop after 10 seconds
                    if (time_stop - time_start) >= 10:
                        print("In sample_bypass_infuse(): Sample infuse timeout !")
                        print("In sample_bypass_infuse(): Turning Pump 2 OFF.")
                        self.rs485_gui_slave.coils_list[4] = 0              # Pump 2 enable set to OFF,                          
                        self.rs485_gui_slave.holding_reg_list[1] = 0        # Switch OFF motor
                        self.rs485_gui_slave.update_gui()
                        self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave                     
                        self.gui_dict['Label_dict']['set_pump_2_status'].configure(text="Pump 2 OFF", bg="orange")
                        self.gui_dict['Label_dict']['infuse_status'].config(text="TIMEOUT !", bg="light blue")
                        break
                    else:
                        self.gui_dict['Label_dict']['infuse_status'].config(text="Timer: " + str(round(time_stop - time_start,2)), bg="light blue")
            # else if checkbox is False , Turn off Pump 2
            else:  
                self.rs485_gui_slave.coils_list[4] = 0          # Pump 2 enable set to OFF                        
                self.rs485_gui_slave.holding_reg_list[1] = 0    # Switch ON motor
                self.rs485_gui_slave.update_gui()
                self.rs485_gui_slave.update_slave_via_reg_list()     # Update slave
                self.gui_dict['Label_dict']['set_pump_2_status'].configure(text="Pump 2 OFF", bg="orange")
                self.gui_dict['Label_dict']['infuse_status'].config(text="Standby", bg="orange")
                print("In sample_bypass_infuse(): Switched OFF Pump 2")          

    def humidity_temperature(self):
        self.rs485_gui_slave.coils_list[1] = 1  
        # self.rs485_gui_slave.gui_dict['Check_dict']['Coil_1_var'].set(1)   # Get humidity & Temperature from Arduino. 
        self.rs485_gui_slave.update_gui()
        self.rs485_gui_slave.update_slave_via_reg_list()
        self.gui_dict['Label_dict']['humidity_value'].configure(text= str(self.rs485_gui_slave.input_reg_list[0]) + "%")     # Update input_reg
        self.gui_dict['Label_dict']['temperature_value'].configure(text= str(self.rs485_gui_slave.input_reg_list[1]))  # Update input_reg
        
    # Function to blink a widget
    def blink(self, widget, blink_num, color):
        for i in range(0,blink_num):
            widget.configure(bg=color)
            self.window.after(100, self.wait_time())
            self.window.update()
            widget.configure(bg="white")
            self.window.after(100, self.wait_time())
            self.window.update()                

    def wait_time(self, *args):
        pass         

### MAIN ############################################################################################################################################
def root_window_bind_callback(*args):
    print("root_window_bind_callback()", *args)           

def on_closing():
    print("destroying main window.")
    root_window.destroy()       # main
    exit()     

def tab_selected(event)   :
    pass

root_window = None
slaves_mcfg = None
mi = None

if __name__ == "__main__":
    # Create the root window
    root_window = Tk()   
    root_window.title('DigiFoods - Inline Sensing')       # Set window title    
    window_width = 1600
    window_height = 1000
    root_window.geometry(str(window_width) + "x" + str(window_height))     # Set window size width x height   1600x1000
    # root_window.geometry("1600x1000")     # Set window size width x height   
    root_window.config(background = "white")     #Set window background color  
    root_window.columnconfigure( 0, weight = 1 ) # Stretch Column 0 to fit width.
    root_window.rowconfigure( 0, weight = 1 ) # Stretch row 0 to fit height. 
    root_window.resizable(width=False, height=False)         # This makes the GUI of fixed size and prevents resizing.

    slaves_mcfg = Slaves_Modbus_Config()       # Get configurations of all slaves (read xlsx file)
    slaves_mcfg.get_config()
    mi = Modbus_Interface()     # Create a RS485 Modbus RTU interface with baud rate, 8N1 ...etc. 

    # Notebook widget
    notebook = ttk.Notebook(root_window)

    # # Place frames for each slave.
    slave_1 = rs485_gui_slave(window = root_window, slave_number = 3, modbus_interface = mi, slaves_mcfg = slaves_mcfg, color = "white")
    slave_1.gen_slave_modbus_gui()
    slave_1.canvas.grid(row = 0, column = 1, sticky = "nw",  columnspan = 1)        
    slave_1.vbar.grid(row = 0, column = 2, sticky = "ns", columnspan = 1, rowspan = 1)  
    
    # slave_2 = rs485_gui_slave(window = root_window, slave_number = 2, modbus_interface = mi, slaves_mcfg = slaves_mcfg, color="light goldenrod")
    # slave_2.gen_slave_modbus_gui()
    # slave_2.canvas.grid(row = 0, column = 2, sticky = "nw", columnspan = 1)           
    # slave_2.vbar.grid(row = 0, column = 3, sticky="ns", columnspan = 1, rowspan=1) 

    # Tab 1 : For sample extraction from the bypass with Y strainer    
    tab_1_sample_bypass_window = ttk.Frame(notebook, border = 2, height = window_height, width = window_width, padding=1)
    sample_bypass = SAMPLE_BYPASS(window = root_window, rs485_gui_slave = slave_1)    

    # tab_2_sample_bypass_window = ttk.Frame(notebook, border = 2, height = window_height, width = window_width, padding=1)
    # sample_bypass_2 = SAMPLE_BYPASS(window  = root_window, rs485_gui_slave = slave_2)      

    root_window.bind('<Return>', root_window_bind_callback )            # This gets the values entered in the gui.
    root_window.lift()       # Bring window forwards
    # root_window.attributes('-topmost', True)
    root_window.protocol("WM_DELETE_WINDOW", on_closing)            # Let the window wait for any events

    s = ttk.Style()
    s.configure('TNotebook.Tab', font=('URW Gothic L','11','bold') )        # Gothic <3 :D !

    notebook.add(tab_1_sample_bypass_window, text='  Sample Bypass  ')    
    # notebook.add(tab_2_sample_bypass_window, text='  Sample Bypass  2')   

    notebook.grid(row=0, column=0)

    notebook.bind("<<NotebookTabChanged>>", tab_selected)       # Bind a monitor to check if we change between Tabs.

    # root_window.grid_columnconfigure((0,1), weight=2, uniform="column")   # This spaces the frame equally in columns    

    root_window.mainloop()       # Blocking function.        


# DUMP
