
# import all components from the tkinter library
from tkinter import *
# from tkinter import filedialog
# from tkinter.filedialog import asksaveasfile
# from os import walk
# from tkinter import messagebox
import tkinter as tk
# import tkinter.font as tkFont
from tkinter import ttk
from datetime import date
import copy
from datetime import datetime
import time 
from slaves_modbus_configuration import*
import time
from pymodbus.client import ModbusSerialClient
from modbus_interface import Modbus_Interface
from watchpoints import watch
from rs485_gui_slave import*

### CAVEATS
# modbus cannot handle floating point and negative value data. 
# So for now, floating point values are generated by dividing the variable by 10 and multiplying by 10 to send over modbus as uint16_t 
# WE are considering ONLY upto one place after decimal for all floating point values.

class SAMPLE_BYPASS():
    def __init__(self, window  = None, rs485_gui_slave = None):
        # Enable module
        # Auto / debug mode : check button
        # tare load cell: Button + Label
        # get_weight: Buttom + Label
        # Set/ Entry box for desired target sample volume/weight
        # Start/ stop sample withdraw, given a flow rate/ PWM value, Pumps to run until we withdraw 150ml of sample
        # Some progress bar to monitor the level/ weight of the sample in the bottle. 
        # Start/ stop sample infusion into centrifuge, given a flow rate/ PWM value. 
        # Same progress bar to denote the sample/ weight level in the bottle
        # Get Humidity and Temperature info, lowest priority 
                
        self.window = window
        # self.data_exchange = data_exchange              
        self.rs485_gui_slave = rs485_gui_slave                
        self.color = "#d9d9d9"    # Deafult gray color of a widget print("Default color = ", self.gui_dict['Check_dict']['enable_sample_bypass'].cget("bg"))              
        self.gui_dict =  {'Label_dict':{}, 'Text_dict':{}, 'Button_dict':{}, 'Entry_dict':{}, 'Check_dict':{}, 'Drop_down_dict':{}, 'Radio_dict':{}, 'Progress_bar':{} }
        self.gen_sample_bypass_gui()        

    def gen_sample_bypass_gui(self):
        self.canvas_height = 500
        self.canvas_width = 500 
        self.canvas = tk.Canvas(self.window, bg="white", height = self.canvas_height, width = self.canvas_width, background= "white",  highlightthickness = 5)  
        self.frame = tk.Frame(self.canvas, width = self.canvas_width-10, height = self.canvas_height-10, background= self.color)        
        self.canvas.create_window( 5, 5, window = self.frame, anchor=tk.NW )         

        width = 40    
        self.gui_dict['Check_dict']['enable_sample_bypass_IntVar'] = IntVar()
        self.gui_dict['Check_dict']['enable_sample_bypass'] = Checkbutton(self.frame, 
                                                                            text="RUN: Sample bypass",
                                                                            variable=self.gui_dict['Check_dict']['enable_sample_bypass_IntVar'],
                                                                            onvalue=True,
                                                                            offvalue=False,
                                                                            height=1, 
                                                                            width = width,
                                                                            command=self.sample_bypass_enable)
                                                                         
        self.gui_dict['Radio_dict']['auto_debug_IntVar'] = StringVar(value="auto")
        self.gui_dict['Radio_dict']['auto'] = tk.Radiobutton(self.frame, text="Auto ", variable=self.gui_dict['Radio_dict']['auto_debug_IntVar'], value="auto", height=1, width = width)
        self.gui_dict['Radio_dict']['debug'] = tk.Radiobutton(self.frame, text="Debug", variable=self.gui_dict['Radio_dict']['auto_debug_IntVar'], value="debug", height=1, width = width)                                                                           
        self.gui_dict['Button_dict']['sample_bypass_start'] = Button(self.frame,
                                                                    text="Start",
                                                                    command=self.sample_bypass_start, 
                                                                    height=1, width = width)

        self.gui_dict['Button_dict']['tare'] = Button(self.frame, text="Tare load cell", command=self.sample_bypass_tare, height=1, width = width)
        self.gui_dict['Button_dict']['get_weight'] = Button(self.frame, text=" Get sample weight ",  command=self.sample_bypass_get_sample_weight, height=1, width = width)
        self.gui_dict['Label_dict']['get_weight'] = Label(self.frame, text="### grams")

        self.gui_dict['Label_dict']['set_weight_withdraw'] = Label(self.frame, text="Set sample weight to withdraw (0 to 200 grams)", wraplength=400, width = width)
        self.gui_dict['Entry_dict']['set_weight_withdraw_DoubleVar'] = DoubleVar(value=0.0)
        self.gui_dict['Entry_dict']['set_weight_withdraw'] = Entry(self.frame, textvariable=self.gui_dict['Entry_dict']['set_weight_withdraw_DoubleVar'], width=20)

        self.gui_dict['Label_dict']['set_weight_infuse'] = Label(self.frame, text="Set sample weight to infuse (0 to <150 grams)", wraplength=400, width = width)
        self.gui_dict['Entry_dict']['set_weight_infuse_DoubleVar'] = DoubleVar(value=0.0)
        self.gui_dict['Entry_dict']['set_weight_infuse'] = Entry(self.frame, textvariable=self.gui_dict['Entry_dict']['set_weight_infuse_DoubleVar'], width=20)        

        self.gui_dict['Label_dict']['set_pump_1_rpm'] = Label(self.frame, text="Set Pump 1 RPM % (0 to 100)", wraplength=250, width = width)
        self.gui_dict['Entry_dict']['set_pump_1_rpm_DoubleVar'] = DoubleVar(value=0)
        self.gui_dict['Entry_dict']['set_pump_1_rpm'] = Entry(self.frame, textvariable=self.gui_dict['Entry_dict']['set_pump_1_rpm_DoubleVar'], width=20)

        self.gui_dict['Label_dict']['set_pump_2_rpm'] = Label(self.frame, text="Set Pump 2 RPM % (0 to 100)", wraplength=250, width = width)
        self.gui_dict['Entry_dict']['set_pump_2_rpm_DoubleVar'] = DoubleVar(value=0)
        self.gui_dict['Entry_dict']['set_pump_2_rpm'] = Entry(self.frame, textvariable=self.gui_dict['Entry_dict']['set_pump_2_rpm_DoubleVar'], width=20)
        
        # Withdraw
        self.gui_dict['Check_dict']['start_stop_withdraw_IntVar'] = IntVar(value=0)
        self.gui_dict['Check_dict']['start_stop_withdraw'] = Checkbutton(self.frame,
                                                                        text="   WITHDRAW Sample: Start / Stop",
                                                                        variable=self.gui_dict['Check_dict']['start_stop_withdraw_IntVar'], 
                                                                        onvalue=1,
                                                                        offvalue=0,
                                                                        command=self.sample_bypass_withdraw,
                                                                        height=1,
                                                                        width = width)
        self.gui_dict['Progress_bar']['withdraw_progress'] = ttk.Progressbar(self.frame, orient='horizontal', length=400,mode="determinate")

        # Infuse
        self.gui_dict['Check_dict']['start_stop_infuse_IntVar'] = IntVar(value=0)
        self.gui_dict['Check_dict']['start_stop_infuse'] = Checkbutton(self.frame,
                                                                        text="   INFUSE Sample: Start / Stop",
                                                                        variable=self.gui_dict['Check_dict']['start_stop_infuse_IntVar'], 
                                                                        onvalue=1,
                                                                        offvalue=0,
                                                                        command=self.sample_bypass_infuse,
                                                                        height=1,
                                                                        width = width)
        self.gui_dict['Progress_bar']['infuse_progress'] = ttk.Progressbar(self.frame, orient='horizontal', length=400,mode="determinate")

        self.gui_dict['Label_dict']['humidity_&_temperature'] = Button(self.frame, text="Humidity (RH) \n Temperature (deg C)", command=self.humidity_temperature, width = width)
        self.gui_dict['Label_dict']['humidity_value'] = Label(self.frame, text=" (%)")        
        self.gui_dict['Label_dict']['temperature_value'] = Label(self.frame, text="### deg C")        

        # Place all the widgets on the self.frame.
        self.canvas.grid(row=0, column=0, sticky="nw", padx=5, pady=50)
        self.gui_dict['Check_dict']['enable_sample_bypass'].grid(row = 0, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Radio_dict']['auto'].grid(row = 1, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Radio_dict']['debug'].grid(row = 2, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Button_dict']['sample_bypass_start'].grid(row = 3, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Button_dict']['tare'].grid(row = 4, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Button_dict']['get_weight'].grid(row = 5, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['get_weight'].grid(row = 5, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['set_weight_withdraw'].grid(row = 6, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Entry_dict']['set_weight_withdraw'].grid(row = 6, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['set_weight_infuse'].grid(row = 7, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Entry_dict']['set_weight_infuse'].grid(row = 7, column = 1, sticky = "nw", pady = 2, columnspan = 1)                    
        
        self.gui_dict['Label_dict']['set_pump_1_rpm'].grid(row = 8, column = 0, sticky = "nw", pady = 2, columnspan = 1)        
        self.gui_dict['Entry_dict']['set_pump_1_rpm'].grid(row = 8, column = 1, sticky = "nw", pady = 2, columnspan = 1)        
        self.gui_dict['Label_dict']['set_pump_2_rpm'].grid(row = 9, column = 0, sticky = "nw", pady = 2, columnspan = 1)        
        self.gui_dict['Entry_dict']['set_pump_2_rpm'].grid(row = 9, column = 1, sticky = "nw", pady = 2, columnspan = 1)        
        
        self.gui_dict['Check_dict']['start_stop_withdraw'].grid(row = 10, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Progress_bar']['withdraw_progress'].grid(row = 11, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Check_dict']['start_stop_infuse'].grid(row = 12, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Progress_bar']['infuse_progress'].grid(row = 13, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['humidity_&_temperature'].grid(row = 14, column = 0, sticky = "nw", pady = 2, columnspan = 1, rowspan = 2)
        self.gui_dict['Label_dict']['humidity_value'].grid(row = 14, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        # self.gui_dict['Label_dict']['temperature'].grid(row = 15, column = 0, sticky = "nw", pady = 2, columnspan = 1)
        self.gui_dict['Label_dict']['temperature_value'].grid(row = 15, column = 1, sticky = "nw", pady = 2, columnspan = 1)
        print("Complete gen_gui()")

    def sample_bypass_enable(self):
        pass

    def sample_bypass_start(self):
        pass
    
    # Function to Tare the load cell.
    def sample_bypass_tare(self):
        self.rs485_gui_slave.coils_list[5] = 1                
        self.rs485_gui_slave.update_gui()
        self.rs485_gui_slave.update_slave_reg_list()

    # Function to get the sample weight, default in arduino code is to get 5 sample and return average.
    def sample_bypass_get_sample_weight(self):
        self.rs485_gui_slave.coils_list[2] = 1                
        self.rs485_gui_slave.update_gui()
        self.rs485_gui_slave.update_slave_reg_list()

    def sample_bypass_withdraw(self): 
        current_weight = self.rs485_gui_slave.input_reg_list[2]     # Update the input reg
        self.rs485_gui_slave.update_gui()
        self.rs485_gui_slave.update_slave_reg_list()     # Get values from registers of slave        

        # Get the weight entered in the Entry box.
        try:
            target_weight = float(self.gui_dict['Entry_dict']['set_weight_withdraw'].get())
        except:
            print("In sample_bypass_withdraw(): Invalid sample weight entered. ")            
            # Flash red - white is target_weight entered was NOT OK
            for i in range(0,2):
                self.gui_dict['Entry_dict']['set_weight_withdraw'].configure(bg="red")
                self.window.after(100, self.wait_time())
                self.window.update()
                self.gui_dict['Entry_dict']['set_weight_withdraw'].configure(bg="white")
                self.window.after(100, self.wait_time())
                self.window.update()

        # check if the user entered weight is inside limits. hard coded for now.
        if (0 < target_weight and target_weight < 200.0):
            # Flash green - white is value entered was OK
            for i in range(0,2):
                self.gui_dict['Entry_dict']['set_weight_withdraw'].configure(bg="light green")
                self.window.after(100, self.wait_time())
                self.window.update()
                self.gui_dict['Entry_dict']['set_weight_withdraw'].configure(bg="white")
                self.window.after(100, self.wait_time())
                self.window.update()
        else:
            # Flash orange - white is target_weight entered was not in limits.
            for i in range(0,2):
                self.gui_dict['Entry_dict']['set_weight_withdraw'].configure(bg="orange")
                self.window.after(100, self.wait_time())
                self.window.update()
                self.gui_dict['Entry_dict']['set_weight_withdraw'].configure(bg="white")
                self.window.after(100, self.wait_time())
                self.window.update()  
                return                  
        
        print("In sample_bypass_withdraw(): Sample weight to withdraw = ", target_weight, " grams")        

        # We need to check of the present weight is sufficient to withdraw more sample !
        if self.gui_dict['Check_dict']['start_stop_withdraw_IntVar'].get() == 1 and (target_weight + current_weight)<= 200.0 :
            # Enable the pump to withdraw with a user entered RPM
            # Sanity check of RPM's entered value.
            try:
                pump_1_rpm = int(float(self.gui_dict['Entry_dict']['set_pump_1_rpm'].get()))
            except:
                print("In sample_bypass_withdraw(): Invalid pump 1 rpm entered. ")            
                # Flash red - white if pump RPM is not ok
                for i in range(0,2):
                    self.gui_dict['Entry_dict']['set_pump_1_rpm'].configure(bg="red")
                    self.window.after(100, self.wait_time())
                    self.window.update()
                    self.gui_dict['Entry_dict']['set_pump_1_rpm'].configure(bg="white")
                    self.window.after(100, self.wait_time())
                    self.window.update()            

            # Check if the user enter values within a limit
            if (0 < pump_1_rpm and pump_1_rpm < 100.0):
                for i in range(0,2):
                    self.gui_dict['Entry_dict']['set_pump_1_rpm'].configure(bg="light green")
                    self.window.after(100, self.wait_time())
                    self.window.update()
                    self.gui_dict['Entry_dict']['set_pump_1_rpm'].configure(bg="white")
                    self.window.after(100, self.wait_time())
                    self.window.update()
            else:
                # Flash orange - white is target_weight entered was not in limits
                for i in range(0,2):
                    self.gui_dict['Entry_dict']['set_pump_1_rpm'].configure(bg="orange")
                    self.window.after(100, self.wait_time())
                    self.window.update()
                    self.gui_dict['Entry_dict']['set_pump_1_rpm'].configure(bg="white")
                    self.window.after(100, self.wait_time())
                    self.window.update()
                    return

            self.rs485_gui_slave.coils_list[3] = 1  # Pump 1 enable set to ON                        
            self.rs485_gui_slave.holding_reg_list[0] = pump_1_rpm   # Switch ON motor
            self.rs485_gui_slave.update_gui()
            self.rs485_gui_slave.update_slave_reg_list()     # Update slave

            # Clear the progress bar
            self.gui_dict['Progress_bar']['withdraw_progress']['value'] = 0

            # We need a timeout here.  
            time_start = datetime.now().second
            while True:
                time_stop = datetime.now().second
                current_weight = self.rs485_gui_slave.input_reg_list[2]     # Update the input reg
                self.rs485_gui_slave.update_gui()
                self.rs485_gui_slave.update_slave_reg_list()     # Get values from registers of slave

                # Check if current weight is greater than or equal to target weight
                if target_weight <= current_weight:
                    print("In sample_bypass_withdraw(): Sample target weight withdrawn.")
                    print("In sample_bypass_withdraw(): Turning pump 1 OFF.")
                    self.rs485_gui_slave.coils_list[3] = 0      # Pump 1 enable set to OFF,                          
                    self.rs485_gui_slave.holding_reg_list[0] = 0        # Switch OFF motor
                    self.rs485_gui_slave.update_gui()
                    self.rs485_gui_slave.update_slave_reg_list()     # Update slave 
                    break
                # Else, we update progress bar, and monitor the current weight.
                else:
                    self.gui_dict['Progress_bar']['withdraw_progress']['value'] = int((time_stop - time_start) * 10)     # time progress
                    # self.gui_dict['Progress_bar']['withdraw_progress']['value'] = int((current_weight/target_weight) * 100) # weight progress

                # Break out of the loop after 10 seconds
                if (time_stop - time_start) >= 10:
                    print("In sample_bypass_withdraw(): Sample withdrawal timeout !")
                    break

            # Multiply the target_weight by 10 to send to the slave since modbus cannot handle floating point values.  
            # target_weight = target_weight * 10

        # Turn off pump 1
        else:  
            self.rs485_gui_slave.coils_list[3] = 0          # Pump 1 enable set to OFF            
            # self.rs485_gui_slave.gui_dict['Check_dict']['Coil_3_var'].set(0) 
            self.rs485_gui_slave.holding_reg_list[0] = 0    # Switch ON motor
            self.rs485_gui_slave.update_gui()
            self.rs485_gui_slave.update_slave_reg_list()     # Update slave
            print("In sample_bypass_withdraw(): Switched OFF pump 1")          

    def sample_bypass_infuse(self):
        pass  

    def humidity_temperature(self):
        self.rs485_gui_slave.coils_list[1] = 1  
        # self.rs485_gui_slave.gui_dict['Check_dict']['Coil_1_var'].set(1)   # Get humidity & Temperature from Arduino. 
        self.rs485_gui_slave.update_gui()
        self.rs485_gui_slave.update_slave_reg_list()
        self.gui_dict['Label_dict']['humidity_value'].configure(text= str(self.rs485_gui_slave.input_reg_list[0]) + "%")     # Update input_reg
        self.gui_dict['Label_dict']['temperature_value'].configure(text= str(self.rs485_gui_slave.input_reg_list[1]))  # Update input_reg
        


    def wait_time(self, *args):
        pass         

### MAIN ############################################################################################################################################
def root_window_bind_callback(*args):
    print("root_window_bind_callback()", *args)           

def on_closing():
    print("destroying main window.")
    root_window.destroy()       # main
    exit()     

def tab_selected(event)   :
    pass

root_window = None
slaves_mcfg = None
mi = None

if __name__ == "__main__":
    # Create the root window
    root_window = Tk()   
    root_window.title('DigiFoods - Inline Sensing')       # Set window title    
    window_width = 1600
    window_height = 1000
    root_window.geometry(str(window_width) + "x" + str(window_height))     # Set window size width x height   1600x1000
    # root_window.geometry("1600x1000")     # Set window size width x height   
    root_window.config(background = "white")     #Set window background color  
    root_window.columnconfigure( 0, weight = 1 ) # Stretch Column 0 to fit width.
    root_window.rowconfigure( 0, weight = 1 ) # Stretch row 0 to fit height. 
    root_window.resizable(width=False, height=False)         # This makes the GUI of fixed size and prevents resizing.


    slaves_mcfg = Slaves_Modbus_Config()       # Get configurations of all slaves (read xlsx file)
    slaves_mcfg.get_config()

    mi = Modbus_Interface()     # Create a RS485 Modbus RTU interface with baud rate, 8N1 ...etc. 

    # Notebook widget
    notebook = ttk.Notebook(root_window)

    # # Place frames for each slave.
    slave_1 = rs485_gui_slave(window = root_window, slave_number = 3, modbus_interface = mi, slaves_mcfg = slaves_mcfg, color = "pale turquoise")
    slave_1.gen_slave_modbus_gui()
    slave_1.canvas.grid(row = 0, column = 1, sticky = "nw",  columnspan = 1)        
    slave_1.vbar.grid(row = 0, column = 2, sticky = "ns", columnspan = 1, rowspan = 1)  

    # slave_2 = rs485_gui_slave(window = root_window, slave_number = 2, modbus_interface = mi, slaves_mcfg = slaves_mcfg, color="light goldenrod")
    # slave_2.gen_slave_modbus_gui()
    # slave_2.canvas.grid(row = 0, column = 2, sticky = "nw", columnspan = 1)           
    # slave_2.vbar.grid(row = 0, column = 3, sticky="ns", columnspan = 1, rowspan=1) 

    # Tab 1 : For sample extraction from the bypass with Y strainer    
    tab_1_sample_bypass_window = ttk.Frame(notebook, border = 2, height = window_height, width = window_width, padding=1)
    sample_bypass = SAMPLE_BYPASS(window = root_window, rs485_gui_slave = slave_1)    

    # tab_2_sample_bypass_window = ttk.Frame(notebook, border = 2, height = window_height, width = window_width, padding=1)
    # sample_bypass_2 = SAMPLE_BYPASS(window  = root_window, rs485_gui_slave = slave_2)      

    root_window.bind('<Return>', root_window_bind_callback )            # This gets the values entered in the gui.
    root_window.lift()       # Bring window forwards
    # root_window.attributes('-topmost', True)
    root_window.protocol("WM_DELETE_WINDOW", on_closing)            # Let the window wait for any events

    s = ttk.Style()
    s.configure('TNotebook.Tab', font=('URW Gothic L','11','bold') )        # Gothic <3 :D !

    notebook.add(tab_1_sample_bypass_window, text='  Sample Bypass  ')    
    # notebook.add(tab_2_sample_bypass_window, text='  Sample Bypass  2')   

    notebook.grid(row=0, column=0)

    # notebook.pack()
    notebook.bind("<<NotebookTabChanged>>", tab_selected)       # Bind a monitor to check if we change between Tabs.

    # root_window.grid_columnconfigure((0,2,4), weight=2, uniform="column")   # This spaces the frame equally in columns    

    root_window.mainloop()       # Blocking function.        


# DUMP
